name: get_aboard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 9,19,27,28,29,30 * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 提交互助码
      run: |
        for ((a=1; a <= 15; a++))
        do
            curl http://api.turinglabs.net/api/v1/jd/bean/create/73qwpzbx4mgajmucs65vsdvscaakk7n7w35ivjy/
            curl http://api.turinglabs.net/api/v1/jd/farm/create/e2e5e1be41dd42a3b5f1351f5ede6842/
            curl http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5OTIwMDAwMDAwMzkzODIxNjc=/
            curl http://api.turinglabs.net/api/v1/jd/jxfactory/create/-NleQwfy3EBCb28rb4we-w==/
            curl http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5nQMD2n51XtXl6HxWCE_/
            curl https://code.chiang.fun/api/v1/jd/jdzz/create/ASjFRlqyYyigKAWH42X8/
            curl http://api.turinglabs.net/api/v1/jd/bean/create/mlrdw3aw26j3wys6ppeul6f2s6ucjrxdjsjjhsy/
            curl http://api.turinglabs.net/api/v1/jd/farm/create/4acc2f2105a84821b469a5a8be3ef277/
            curl http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5OTIwMDAwMDAwNDI3Nzc0MzM=/
            curl http://api.turinglabs.net/api/v1/jd/jxfactory/create/dO1sz5uhmIvq42znCw5jcg==/
            curl http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2Ws1XtNl83wDG7CVHU/
            curl https://code.chiang.fun/api/v1/jd/jdzz/create/AUWE5mvmYyjIKCjL-2yhPlg/
            sleep 20m
        done
