name: jd_crazy_python

on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: jd_crazy_python
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: '运行领京豆'
        run: |
          curl ${{ secrets.CRAZY_URL }} -o jd_crazy.js
          node jd_crazy.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: jd_crazy